In [1]:
import pandas as pd
df = pd.read_csv('./data/서울시_우리마을가게_상권분석서비스(신_상권_추정매출)_2020년.csv', encoding='cp949')
df

,기준_년_코드,기준_분기_코드,상권_구분_코드,상권_구분_코드_명,상권_코드,상권_코드_명,서비스_업종_코드,서비스_업종_코드_명,분기당_매출_금액,분기당_매출_건수,...,시간대_건수~24_매출_건수,남성_매출_건수,여성_매출_건수,연령대_10_매출_건수,연령대_20_매출_건수,연령대_30_매출_건수,연령대_40_매출_건수,연령대_50_매출_건수,연령대_60_이상_매출_건수,점포수
0,2020,1,A,골목상권,2110001,이북5도청사,CS100001,한식음식점,673117215,26310,...,561,14980,8039,86,1875,2243,4809,7609,6398,28
1,2020,1,A,골목상권,2110001,이북5도청사,CS100008,분식전문점,87592085,10029,...,0,6377,2972,52,646,1849,2424,2492,1885,9
2,2020,1,A,골목상권,2110001,이북5도청사,CS100009,호프-간이주점,16496685,329,...,150,260,46,0,18,9,67,134,78,6
3,2020,1,A,골목상권,2110001,이북5도청사,CS100010,커피-음료,19442192,1562,...,54,678,773,0,166,345,533,252,155,8
4,2020,1,A,골목상권,2110001,이북5도청사,CS200001,일반교습학원,21617575,72,...,0,24,48,0,0,16,56,0,0,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
144744,2020,4,U,관광특구,1001496,강남 마이스 관광특구,CS300027,섬유제품,971389704,31185,...,856,5768,25417,1111,15614,6853,3873,3166,568,6
144745,2020,4,U,관광특구,1001496,강남 마이스 관광특구,CS300028,화초,409610564,9795,...,12,5050,4262,30,2543,3556,1490,930,763,6
144746,2020,4,U,관광특구,1001496,강남 마이스 관광특구,CS300031,가구,11920008477,6667,...,0,2753,3914,0,306,634,1455,1520,2752,6
144747,2020,4,U,관광특구,1001496,강남 마이스 관광특구,CS300032,가전제품,2123968546,8062,...,210,3726,3652,84,2400,2154,1469,850,418,8
144748,2020,4,U,관광특구,1001496,강남 마이스 관광특구,CS300043,전자상거래업,3808746,170,...,0,39,131,0,5,116,49,0,0,8

In [2]:
df = df[df['상권_코드_명'].str.contains('역')]
df

,기준_년_코드,기준_분기_코드,상권_구분_코드,상권_구분_코드_명,상권_코드,상권_코드_명,서비스_업종_코드,서비스_업종_코드_명,분기당_매출_금액,분기당_매출_건수,...,시간대_건수~24_매출_건수,남성_매출_건수,여성_매출_건수,연령대_10_매출_건수,연령대_20_매출_건수,연령대_30_매출_건수,연령대_40_매출_건수,연령대_50_매출_건수,연령대_60_이상_매출_건수,점포수
12,2020,1,A,골목상권,2110002,독립문역 1번,CS100001,한식음식점,366637605,16912,...,300,9006,7608,17,1255,2166,3341,4849,4985,21
13,2020,1,A,골목상권,2110002,독립문역 1번,CS100005,제과점,435108631,46654,...,3818,16920,28192,288,7297,8848,12197,10170,6312,9
14,2020,1,A,골목상권,2110002,독립문역 1번,CS100007,치킨전문점,127053722,4818,...,1522,2782,1764,14,551,848,1382,1300,449,9
15,2020,1,A,골목상권,2110002,독립문역 1번,CS100008,분식전문점,11911520,1452,...,0,685,757,26,276,343,337,303,155,3
16,2020,1,A,골목상권,2110002,독립문역 1번,CS100010,커피-음료,93062167,12326,...,324,5045,6805,121,3005,2682,2401,2790,848,9
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
144394,2020,4,R,전통시장,2130323,둔촌역전통시장,CS300022,화장품,32047732,397,...,0,88,309,0,0,102,32,149,114,7
144395,2020,4,R,전통시장,2130323,둔촌역전통시장,CS300026,완구,16588858,440,...,175,316,124,5,85,184,76,50,40,3
144396,2020,4,R,전통시장,2130323,둔촌역전통시장,CS300028,화초,3000000,230,...,0,40,173,6,11,94,26,40,36,3
144397,2020,4,R,전통시장,2130323,둔촌역전통시장,CS300029,애완동물,24254965,1844,...,7,890,954,0,216,549,406,490,183,3
144398,2020,4,R,전통시장,2130323,둔촌역전통시장,CS300043,전자상거래업,124521428,5375,...,69,2286,3055,219,208,353,3067,1092,402,3

### 상권코드명만 추출

In [3]:
new_df = pd.DataFrame(df['상권_코드_명'].sort_values().unique(), columns=['상권_코드_명'])
new_df

             상권_코드_명
0       4.19민주묘지역 2번
1              가락시장역
2    가산디지털단지역 1번 출입구
3            가양역 10번
4            가오리역 1번
..               ...
537              회현역
538           회현역 1번
539        효창공원앞역 2번
540        효창공원앞역 5번
541        효창공원앞역 6번

[542 rows x 1 columns]

### 1. 공백을 구분자로 split
#### 공백을 구분자로 분리하기 전에 특정 값들 변경작업

In [4]:
new_df[(new_df['상권_코드_명'].str.contains(' ')) & (new_df['상권_코드_명'].str.split(' ').str[0].str.contains('역')==False)]

                 상권_코드_명
27              경의중앙 신촌역
272  서울축산농협 독산역지점(독산파출소)

In [5]:
new_df.replace({'상권_코드_명':'경의중앙 신촌역'}, {'상권_코드_명':'신촌역'}, inplace=True)
new_df.replace({'상권_코드_명':'서울축산농협 독산역지점(독산파출소)'}, {'상권_코드_명':'독산역'}, inplace=True)
new_df.loc[[27, 272], :]  # 변경됐는지 확인~

    상권_코드_명
27      신촌역
272     독산역

#### 공백을 구분자로 분리하고, 출구번호 사라지면서 나타난 중복값 제거

In [6]:
new_df['상권_코드_명'] = new_df['상권_코드_명'].str.split(' ').str[0]
new_df.drop_duplicates(inplace=True)
new_df

       상권_코드_명
0    4.19민주묘지역
1        가락시장역
2     가산디지털단지역
3          가양역
4         가오리역
..         ...
529        화곡역
533       화랑대역
534        회기역
537        회현역
539     효창공원앞역

[291 rows x 1 columns]

In [7]:
new_df['상권_코드_명'].values

array(['4.19민주묘지역', '가락시장역', '가산디지털단지역', '가양역', '가오리역', '가좌역',
       '강남구청(청담역_8번,', '강남구청역', '강남역', '강남터미널지하도상점가2구역', '강동구청(강동구청역',
       '강동구청역', '강동역', '강변역(테크노마트)', '개롱역', '개봉역', '개화산역', '거여역', '건대입구역',
       '건대입구역(건대)', '신촌역', '경찰병원역', '고덕역', '고려대역', '고속터미널(고속터미널역)',
       '공덕역(공덕오거리)', '공릉역', '공항시장역', '광나루역', '광운대역', '광화문역', '광흥창역',
       '교대역(법원.검찰청)', '구로디지털단지역', '구로역', '구반포역', '구산역', '구역삼세무서', '구의역',
       '구파발역', '국회의사당역(국회의사당)', '군자역', '굽은다리역', '금천구청역', '금호역', '길동역',
       '길음역', '김포공항역(김포공항)', '까치산역', '낙성대역', '남구로역', '남부터미널역', '남성역',
       '남성역골목시장', '남영역', '남태령역(서울전자고등학교)', '내방역', '노량진역', '노량진역(노량진)',
       '노원역', '논현역', '답십리역', '당고개역', '당산역', '대림역', '대림차이나타운(대림역', '대방역',
       '대치역', '대학로(혜화역)', '대흥역', '도봉산역', '도봉역', '독립문역', '독산역', '돌곶이역',
       '동대문역', '동대문역사문화공원역', '동묘앞역', '동묘앞역(동묘)', '둔촌동역', '둔촌역', '둔촌역전통시장',
       '등촌역', '뚝섬역', '뚝섬역교차로', '뚝섬역상점가', '뚝섬유원지역', '마곡역(마곡)', '마들역',
       '마장역', '마천역(마천초등학교)', '마포구청역', '마포역', '망우역', '망원역', '매봉역', '먹골역',
       '면목역', '명동역(명동재미로)', '명일역', '목동역', '몽촌토성역', '문래역', '문래역(문래로데오거리)',
       '문정역', '문현중학교(장지역', '미아사거리역', '미아역', '발산역', '발산역(마곡)', '방배역',
       '방이역', '방학역', '방화역', '보라매역', '보문역', '봉은사역', '봉천역', '북창동(시청역_6번)',
       '북촌(안국역)', '북한산보국문역', '북한산우이역', '불광역', '사가정역', '사당역', '사당역(사당)',
       '삼각지역', '삼성역', '삼성중앙역', '삼양사거리역', '삼전역', '상계역', '상도역', '상봉역',
       '상수역', '상수역(홍대)', '상왕십리역', '상월곡역', '새절역', '서강대역', '서대문역', '서빙고역',
       '서울대입구역', '서울숲역', '서울역', '서초역', '서촌(경복궁역)', '석계역', '석수역', '석촌고분역',
       '석촌역', '석촌역(석촌호수)', '선릉역', '선유도역', '선정릉역', '성수역', '성신여대입구역',
       '솔밭공원역', '송정역', '송파나루역', '송파사거리(송파역)', '송파역', '수락산역', '수색역', '수서역',
       '수유역', '숙대입구역', '숙대입구역(남영역,', '숭실대입구역', '시청역_1번', '시청역_8번', '신금호역',
       '신길역', '신내역', '신논현역', '신당역', '신대방삼거리역', '신대방역', '신도림역', '신림역',
       '신림역(신림)', '신목동역', '신방화역', '신사역', '신설동역', '신용산역(용산역)', '신정네거리역',
       '신정역', '신촌역(신촌역,', '신풍역', '쌍문시장(쌍문역골목시장)', '쌍문역1번(쌍리단길)',
       '쌍문역동측상점가', '쌍문역둘리상점가', '아차산역', '아현역', '안암역', '암사역',
       '압구정로데오역(압구정로데오)', '압구정역', '애오개역', '약수역', '양재시민의숲역(양재동꽃시장,', '양재역',
       '양천향교역', '양평역', '어린이대공원역', '언주역', '언주역(차병원)', '여의도역(여의도)', '역삼역',
       '역삼월드메르디앙아파트', '역촌노인복지관', '역촌역', '역촌중앙시장', '연신내역', '염창역', '영등포구청역',
       '영등포시장역', '영등포역', '영등포역(영등포)', '영등포역지하도상점가', '오금역', '오류동역', '오목교역',
       '옥수역', '온수역', '왕십리역', '왕십리역(왕십리)', '외대앞역', '용산전자상가(용산역)', '우장산역',
       '월계역', '월곡역', '월드컵경기장역(월드컵경기장)', '을지로3가역', '을지로4가역', '을지로입구역',
       '응암역', '이대역', '이수역', '이태원(이태원역)', '이태원역', '이화여대(이대역,', '잠실나루역',
       '잠실새내역(신천)', '잠실역', '잠원역', '장승배기역', '장지역(가든파이브)', '장한평역(장한평)',
       '정릉역', '제기동역', '종각역', '종로3가역', '종로5가역', '중곡역', '중랑역', '중화역', '증산역',
       '창동역', '창동역상점가', '창신역', '천왕역', '천호역', '청계산입구역', '청구역', '청담역',
       '청량리역(청량리)', '총신대입구역(이수,', '충무로역', '충정로역', '태릉입구역', '학동역', '한강진역',
       '한성대입구역', '한성백제역', '한양대역', '한티역', '합정역', '행당역', '혜화역', '홍대입구역',
       '홍대입구역(홍대)', '홍제역', '화계역', '화곡역', '화랑대역', '회기역', '회현역', '효창공원앞역'],
      dtype=object)

### 2. '역'이 포함되어 있는 역이 아닌 행 검색하고 삭제~
#### 조금 노가다. 다른 방식 나중에 찾아보기

In [8]:
del_rows = new_df[(new_df['상권_코드_명'] == '역촌중앙시장')|(new_df['상권_코드_명'] == '강남터미널지하도상점가2구역')\
       |(new_df['상권_코드_명'] == '구역삼세무서')|(new_df['상권_코드_명'] == '역삼월드메르디앙아파트')\
       |(new_df['상권_코드_명'] == '역촌노인복지관')].index
del_rows

Int64Index([13, 54, 405, 406, 409], dtype='int64')

In [9]:
new_df.drop(del_rows, axis=0, inplace=True)
new_df.reset_index(drop=True, inplace=True)
new_df

       상권_코드_명
0    4.19민주묘지역
1        가락시장역
2     가산디지털단지역
3          가양역
4         가오리역
..         ...
281        화곡역
282       화랑대역
283        회기역
284        회현역
285     효창공원앞역

[286 rows x 1 columns]

In [10]:
# 값 확인
new_df['상권_코드_명'].values

array(['4.19민주묘지역', '가락시장역', '가산디지털단지역', '가양역', '가오리역', '가좌역',
       '강남구청(청담역_8번,', '강남구청역', '강남역', '강동구청(강동구청역', '강동구청역', '강동역',
       '강변역(테크노마트)', '개롱역', '개봉역', '개화산역', '거여역', '건대입구역', '건대입구역(건대)',
       '신촌역', '경찰병원역', '고덕역', '고려대역', '고속터미널(고속터미널역)', '공덕역(공덕오거리)',
       '공릉역', '공항시장역', '광나루역', '광운대역', '광화문역', '광흥창역', '교대역(법원.검찰청)',
       '구로디지털단지역', '구로역', '구반포역', '구산역', '구의역', '구파발역', '국회의사당역(국회의사당)',
       '군자역', '굽은다리역', '금천구청역', '금호역', '길동역', '길음역', '김포공항역(김포공항)',
       '까치산역', '낙성대역', '남구로역', '남부터미널역', '남성역', '남성역골목시장', '남영역',
       '남태령역(서울전자고등학교)', '내방역', '노량진역', '노량진역(노량진)', '노원역', '논현역', '답십리역',
       '당고개역', '당산역', '대림역', '대림차이나타운(대림역', '대방역', '대치역', '대학로(혜화역)',
       '대흥역', '도봉산역', '도봉역', '독립문역', '독산역', '돌곶이역', '동대문역', '동대문역사문화공원역',
       '동묘앞역', '동묘앞역(동묘)', '둔촌동역', '둔촌역', '둔촌역전통시장', '등촌역', '뚝섬역',
       '뚝섬역교차로', '뚝섬역상점가', '뚝섬유원지역', '마곡역(마곡)', '마들역', '마장역',
       '마천역(마천초등학교)', '마포구청역', '마포역', '망우역', '망원역', '매봉역', '먹골역', '면목역',
       '명동역(명동재미로)', '명일역', '목동역', '몽촌토성역', '문래역', '문래역(문래로데오거리)', '문정역',
       '문현중학교(장지역', '미아사거리역', '미아역', '발산역', '발산역(마곡)', '방배역', '방이역',
       '방학역', '방화역', '보라매역', '보문역', '봉은사역', '봉천역', '북창동(시청역_6번)',
       '북촌(안국역)', '북한산보국문역', '북한산우이역', '불광역', '사가정역', '사당역', '사당역(사당)',
       '삼각지역', '삼성역', '삼성중앙역', '삼양사거리역', '삼전역', '상계역', '상도역', '상봉역',
       '상수역', '상수역(홍대)', '상왕십리역', '상월곡역', '새절역', '서강대역', '서대문역', '서빙고역',
       '서울대입구역', '서울숲역', '서울역', '서초역', '서촌(경복궁역)', '석계역', '석수역', '석촌고분역',
       '석촌역', '석촌역(석촌호수)', '선릉역', '선유도역', '선정릉역', '성수역', '성신여대입구역',
       '솔밭공원역', '송정역', '송파나루역', '송파사거리(송파역)', '송파역', '수락산역', '수색역', '수서역',
       '수유역', '숙대입구역', '숙대입구역(남영역,', '숭실대입구역', '시청역_1번', '시청역_8번', '신금호역',
       '신길역', '신내역', '신논현역', '신당역', '신대방삼거리역', '신대방역', '신도림역', '신림역',
       '신림역(신림)', '신목동역', '신방화역', '신사역', '신설동역', '신용산역(용산역)', '신정네거리역',
       '신정역', '신촌역(신촌역,', '신풍역', '쌍문시장(쌍문역골목시장)', '쌍문역1번(쌍리단길)',
       '쌍문역동측상점가', '쌍문역둘리상점가', '아차산역', '아현역', '안암역', '암사역',
       '압구정로데오역(압구정로데오)', '압구정역', '애오개역', '약수역', '양재시민의숲역(양재동꽃시장,', '양재역',
       '양천향교역', '양평역', '어린이대공원역', '언주역', '언주역(차병원)', '여의도역(여의도)', '역삼역',
       '역촌역', '연신내역', '염창역', '영등포구청역', '영등포시장역', '영등포역', '영등포역(영등포)',
       '영등포역지하도상점가', '오금역', '오류동역', '오목교역', '옥수역', '온수역', '왕십리역',
       '왕십리역(왕십리)', '외대앞역', '용산전자상가(용산역)', '우장산역', '월계역', '월곡역',
       '월드컵경기장역(월드컵경기장)', '을지로3가역', '을지로4가역', '을지로입구역', '응암역', '이대역',
       '이수역', '이태원(이태원역)', '이태원역', '이화여대(이대역,', '잠실나루역', '잠실새내역(신천)',
       '잠실역', '잠원역', '장승배기역', '장지역(가든파이브)', '장한평역(장한평)', '정릉역', '제기동역',
       '종각역', '종로3가역', '종로5가역', '중곡역', '중랑역', '중화역', '증산역', '창동역',
       '창동역상점가', '창신역', '천왕역', '천호역', '청계산입구역', '청구역', '청담역', '청량리역(청량리)',
       '총신대입구역(이수,', '충무로역', '충정로역', '태릉입구역', '학동역', '한강진역', '한성대입구역',
       '한성백제역', '한양대역', '한티역', '합정역', '행당역', '혜화역', '홍대입구역', '홍대입구역(홍대)',
       '홍제역', '화계역', '화곡역', '화랑대역', '회기역', '회현역', '효창공원앞역'], dtype=object)

#### '동대문역사문화공원역'과 '동대문역' 합쳐지기 전에 처리하기

In [11]:
new_df[new_df['상권_코드_명'] == '동대문역사문화공원역']

       상권_코드_명
74  동대문역사문화공원역

### 3. '역'을 구분자로 split

In [12]:
new_df['상권_코드_명'] = new_df['상권_코드_명'].str.split('역').str[0]
new_df['상권_코드_명'].values

array(['4.19민주묘지', '가락시장', '가산디지털단지', '가양', '가오리', '가좌', '강남구청(청담',
       '강남구청', '강남', '강동구청(강동구청', '강동구청', '강동', '강변', '개롱', '개봉', '개화산',
       '거여', '건대입구', '건대입구', '신촌', '경찰병원', '고덕', '고려대', '고속터미널(고속터미널',
       '공덕', '공릉', '공항시장', '광나루', '광운대', '광화문', '광흥창', '교대', '구로디지털단지',
       '구로', '구반포', '구산', '구의', '구파발', '국회의사당', '군자', '굽은다리', '금천구청',
       '금호', '길동', '길음', '김포공항', '까치산', '낙성대', '남구로', '남부터미널', '남성', '남성',
       '남영', '남태령', '내방', '노량진', '노량진', '노원', '논현', '답십리', '당고개', '당산',
       '대림', '대림차이나타운(대림', '대방', '대치', '대학로(혜화', '대흥', '도봉산', '도봉', '독립문',
       '독산', '돌곶이', '동대문', '동대문', '동묘앞', '동묘앞', '둔촌동', '둔촌', '둔촌', '등촌',
       '뚝섬', '뚝섬', '뚝섬', '뚝섬유원지', '마곡', '마들', '마장', '마천', '마포구청', '마포',
       '망우', '망원', '매봉', '먹골', '면목', '명동', '명일', '목동', '몽촌토성', '문래', '문래',
       '문정', '문현중학교(장지', '미아사거리', '미아', '발산', '발산', '방배', '방이', '방학',
       '방화', '보라매', '보문', '봉은사', '봉천', '북창동(시청', '북촌(안국', '북한산보국문',
       '북한산우이', '불광', '사가정', '사당', '사당', '삼각지', '삼성', '삼성중앙', '삼양사거리',
       '삼전', '상계', '상도', '상봉', '상수', '상수', '상왕십리', '상월곡', '새절', '서강대',
       '서대문', '서빙고', '서울대입구', '서울숲', '서울', '서초', '서촌(경복궁', '석계', '석수',
       '석촌고분', '석촌', '석촌', '선릉', '선유도', '선정릉', '성수', '성신여대입구', '솔밭공원',
       '송정', '송파나루', '송파사거리(송파', '송파', '수락산', '수색', '수서', '수유', '숙대입구',
       '숙대입구', '숭실대입구', '시청', '시청', '신금호', '신길', '신내', '신논현', '신당',
       '신대방삼거리', '신대방', '신도림', '신림', '신림', '신목동', '신방화', '신사', '신설동',
       '신용산', '신정네거리', '신정', '신촌', '신풍', '쌍문시장(쌍문', '쌍문', '쌍문', '쌍문',
       '아차산', '아현', '안암', '암사', '압구정로데오', '압구정', '애오개', '약수', '양재시민의숲',
       '양재', '양천향교', '양평', '어린이대공원', '언주', '언주', '여의도', '', '', '연신내',
       '염창', '영등포구청', '영등포시장', '영등포', '영등포', '영등포', '오금', '오류동', '오목교',
       '옥수', '온수', '왕십리', '왕십리', '외대앞', '용산전자상가(용산', '우장산', '월계', '월곡',
       '월드컵경기장', '을지로3가', '을지로4가', '을지로입구', '응암', '이대', '이수', '이태원(이태원',
       '이태원', '이화여대(이대', '잠실나루', '잠실새내', '잠실', '잠원', '장승배기', '장지', '장한평',
       '정릉', '제기동', '종각', '종로3가', '종로5가', '중곡', '중랑', '중화', '증산', '창동',
       '창동', '창신', '천왕', '천호', '청계산입구', '청구', '청담', '청량리', '총신대입구', '충무로',
       '충정로', '태릉입구', '학동', '한강진', '한성대입구', '한성백제', '한양대', '한티', '합정',
       '행당', '혜화', '홍대입구', '홍대입구', '홍제', '화계', '화곡', '화랑대', '회기', '회현',
       '효창공원앞'], dtype=object)

### 4. 괄호 앞부분 없애기

In [13]:
new_df['상권_코드_명'] = new_df['상권_코드_명'].str.split('\(').str[-1]  # 괄호 뒷부분이 역 이름이니까
new_df['상권_코드_명'].values

array(['4.19민주묘지', '가락시장', '가산디지털단지', '가양', '가오리', '가좌', '청담', '강남구청',
       '강남', '강동구청', '강동구청', '강동', '강변', '개롱', '개봉', '개화산', '거여', '건대입구',
       '건대입구', '신촌', '경찰병원', '고덕', '고려대', '고속터미널', '공덕', '공릉', '공항시장',
       '광나루', '광운대', '광화문', '광흥창', '교대', '구로디지털단지', '구로', '구반포', '구산',
       '구의', '구파발', '국회의사당', '군자', '굽은다리', '금천구청', '금호', '길동', '길음',
       '김포공항', '까치산', '낙성대', '남구로', '남부터미널', '남성', '남성', '남영', '남태령',
       '내방', '노량진', '노량진', '노원', '논현', '답십리', '당고개', '당산', '대림', '대림',
       '대방', '대치', '혜화', '대흥', '도봉산', '도봉', '독립문', '독산', '돌곶이', '동대문',
       '동대문', '동묘앞', '동묘앞', '둔촌동', '둔촌', '둔촌', '등촌', '뚝섬', '뚝섬', '뚝섬',
       '뚝섬유원지', '마곡', '마들', '마장', '마천', '마포구청', '마포', '망우', '망원', '매봉',
       '먹골', '면목', '명동', '명일', '목동', '몽촌토성', '문래', '문래', '문정', '장지',
       '미아사거리', '미아', '발산', '발산', '방배', '방이', '방학', '방화', '보라매', '보문',
       '봉은사', '봉천', '시청', '안국', '북한산보국문', '북한산우이', '불광', '사가정', '사당',
       '사당', '삼각지', '삼성', '삼성중앙', '삼양사거리', '삼전', '상계', '상도', '상봉', '상수',
       '상수', '상왕십리', '상월곡', '새절', '서강대', '서대문', '서빙고', '서울대입구', '서울숲',
       '서울', '서초', '경복궁', '석계', '석수', '석촌고분', '석촌', '석촌', '선릉', '선유도',
       '선정릉', '성수', '성신여대입구', '솔밭공원', '송정', '송파나루', '송파', '송파', '수락산',
       '수색', '수서', '수유', '숙대입구', '숙대입구', '숭실대입구', '시청', '시청', '신금호', '신길',
       '신내', '신논현', '신당', '신대방삼거리', '신대방', '신도림', '신림', '신림', '신목동',
       '신방화', '신사', '신설동', '신용산', '신정네거리', '신정', '신촌', '신풍', '쌍문', '쌍문',
       '쌍문', '쌍문', '아차산', '아현', '안암', '암사', '압구정로데오', '압구정', '애오개', '약수',
       '양재시민의숲', '양재', '양천향교', '양평', '어린이대공원', '언주', '언주', '여의도', '', '',
       '연신내', '염창', '영등포구청', '영등포시장', '영등포', '영등포', '영등포', '오금', '오류동',
       '오목교', '옥수', '온수', '왕십리', '왕십리', '외대앞', '용산', '우장산', '월계', '월곡',
       '월드컵경기장', '을지로3가', '을지로4가', '을지로입구', '응암', '이대', '이수', '이태원',
       '이태원', '이대', '잠실나루', '잠실새내', '잠실', '잠원', '장승배기', '장지', '장한평', '정릉',
       '제기동', '종각', '종로3가', '종로5가', '중곡', '중랑', '중화', '증산', '창동', '창동',
       '창신', '천왕', '천호', '청계산입구', '청구', '청담', '청량리', '총신대입구', '충무로',
       '충정로', '태릉입구', '학동', '한강진', '한성대입구', '한성백제', '한양대', '한티', '합정',
       '행당', '혜화', '홍대입구', '홍대입구', '홍제', '화계', '화곡', '화랑대', '회기', '회현',
       '효창공원앞'], dtype=object)

### 5. '역'으로 분리할 때 사라졌던 역삼역, 역촌역 추가

In [14]:
new_df[new_df['상권_코드_명']=='']

    상권_코드_명
208
209

In [15]:
new_df.loc[208, ['상권_코드_명']] = '역삼'
new_df.loc[209, ['상권_코드_명']] = '역촌'

In [16]:
new_df.loc[208, ['상권_코드_명']]

상권_코드_명    역삼
Name: 208, dtype: object

In [17]:
new_df.loc[209, ['상권_코드_명']]

상권_코드_명    역촌
Name: 209, dtype: object

#### 동대문역사문화공원역 주의

In [18]:
new_df.loc[74, '상권_코드_명']

'동대문'

In [19]:
new_df.loc[74, '상권_코드_명'] = '동대문역사문화공원'
new_df.loc[74, '상권_코드_명']

'동대문역사문화공원'

#### 마지막으로 값 확인

In [20]:
new_df['상권_코드_명'].values

array(['4.19민주묘지', '가락시장', '가산디지털단지', '가양', '가오리', '가좌', '청담', '강남구청',
       '강남', '강동구청', '강동구청', '강동', '강변', '개롱', '개봉', '개화산', '거여', '건대입구',
       '건대입구', '신촌', '경찰병원', '고덕', '고려대', '고속터미널', '공덕', '공릉', '공항시장',
       '광나루', '광운대', '광화문', '광흥창', '교대', '구로디지털단지', '구로', '구반포', '구산',
       '구의', '구파발', '국회의사당', '군자', '굽은다리', '금천구청', '금호', '길동', '길음',
       '김포공항', '까치산', '낙성대', '남구로', '남부터미널', '남성', '남성', '남영', '남태령',
       '내방', '노량진', '노량진', '노원', '논현', '답십리', '당고개', '당산', '대림', '대림',
       '대방', '대치', '혜화', '대흥', '도봉산', '도봉', '독립문', '독산', '돌곶이', '동대문',
       '동대문역사문화공원', '동묘앞', '동묘앞', '둔촌동', '둔촌', '둔촌', '등촌', '뚝섬', '뚝섬',
       '뚝섬', '뚝섬유원지', '마곡', '마들', '마장', '마천', '마포구청', '마포', '망우', '망원',
       '매봉', '먹골', '면목', '명동', '명일', '목동', '몽촌토성', '문래', '문래', '문정', '장지',
       '미아사거리', '미아', '발산', '발산', '방배', '방이', '방학', '방화', '보라매', '보문',
       '봉은사', '봉천', '시청', '안국', '북한산보국문', '북한산우이', '불광', '사가정', '사당',
       '사당', '삼각지', '삼성', '삼성중앙', '삼양사거리', '삼전', '상계', '상도', '상봉', '상수',
       '상수', '상왕십리', '상월곡', '새절', '서강대', '서대문', '서빙고', '서울대입구', '서울숲',
       '서울', '서초', '경복궁', '석계', '석수', '석촌고분', '석촌', '석촌', '선릉', '선유도',
       '선정릉', '성수', '성신여대입구', '솔밭공원', '송정', '송파나루', '송파', '송파', '수락산',
       '수색', '수서', '수유', '숙대입구', '숙대입구', '숭실대입구', '시청', '시청', '신금호', '신길',
       '신내', '신논현', '신당', '신대방삼거리', '신대방', '신도림', '신림', '신림', '신목동',
       '신방화', '신사', '신설동', '신용산', '신정네거리', '신정', '신촌', '신풍', '쌍문', '쌍문',
       '쌍문', '쌍문', '아차산', '아현', '안암', '암사', '압구정로데오', '압구정', '애오개', '약수',
       '양재시민의숲', '양재', '양천향교', '양평', '어린이대공원', '언주', '언주', '여의도', '역삼',
       '역촌', '연신내', '염창', '영등포구청', '영등포시장', '영등포', '영등포', '영등포', '오금',
       '오류동', '오목교', '옥수', '온수', '왕십리', '왕십리', '외대앞', '용산', '우장산', '월계',
       '월곡', '월드컵경기장', '을지로3가', '을지로4가', '을지로입구', '응암', '이대', '이수', '이태원',
       '이태원', '이대', '잠실나루', '잠실새내', '잠실', '잠원', '장승배기', '장지', '장한평', '정릉',
       '제기동', '종각', '종로3가', '종로5가', '중곡', '중랑', '중화', '증산', '창동', '창동',
       '창신', '천왕', '천호', '청계산입구', '청구', '청담', '청량리', '총신대입구', '충무로',
       '충정로', '태릉입구', '학동', '한강진', '한성대입구', '한성백제', '한양대', '한티', '합정',
       '행당', '혜화', '홍대입구', '홍대입구', '홍제', '화계', '화곡', '화랑대', '회기', '회현',
       '효창공원앞'], dtype=object)

In [21]:
new_df

      상권_코드_명
0    4.19민주묘지
1        가락시장
2     가산디지털단지
3          가양
4         가오리
..        ...
281        화곡
282       화랑대
283        회기
284        회현
285     효창공원앞

[286 rows x 1 columns]

#### 매출데이터에 '역'이 없어서 누락된 역('버티고개', 'DMC(디지털미디어시티)') 추가

In [22]:
new_df.loc[286, '상권_코드_명'] = '버티고개'
new_df.loc[287, '상권_코드_명'] = '디지털미디어시티'  # 매출 데이터에는 'DMC(디지털미디어시티)'라고 되어있음
new_df.drop_duplicates(inplace=True)
new_df

      상권_코드_명
0    4.19민주묘지
1        가락시장
2     가산디지털단지
3          가양
4         가오리
..        ...
283        회기
284        회현
285     효창공원앞
286      버티고개
287  디지털미디어시티

[254 rows x 1 columns]

#### 다른 사람이 추출한 역정보와 비교

In [23]:
another_df = pd.read_csv('./최종추출_역정보.csv', encoding='cp949')
another_df

       상권_코드_명
0          독립문
1         종로5가
2           혜화
3          동대문
4           창신
..         ...
249         역촌
250  동대문역사문화공원
251       버티고개
252         역삼
253   디지털미디어시티

[254 rows x 1 columns]

In [24]:
another_df = another_df.sort_values(by ='상권_코드_명').reset_index(drop = True)
another_df

      상권_코드_명
0    4.19민주묘지
1        가락시장
2     가산디지털단지
3          가양
4         가오리
..        ...
249        화곡
250       화랑대
251        회기
252        회현
253     효창공원앞

[254 rows x 1 columns]

In [25]:
new_df = new_df.sort_values(by ='상권_코드_명').reset_index(drop = True)
new_df

      상권_코드_명
0    4.19민주묘지
1        가락시장
2     가산디지털단지
3          가양
4         가오리
..        ...
249        화곡
250       화랑대
251        회기
252        회현
253     효창공원앞

[254 rows x 1 columns]

In [26]:
A = pd.concat([another_df,new_df], axis = 1)

In [27]:
pd.set_option('display.max_row', 500)  # 주석처리
A

       상권_코드_명    상권_코드_명
0     4.19민주묘지   4.19민주묘지
1         가락시장       가락시장
2      가산디지털단지    가산디지털단지
3           가양         가양
4          가오리        가오리
5           가좌         가좌
6           강남         강남
7         강남구청       강남구청
8           강동         강동
9         강동구청       강동구청
10          강변         강변
11          개롱         개롱
12          개봉         개봉
13         개화산        개화산
14          거여         거여
15        건대입구       건대입구
16         경복궁        경복궁
17        경찰병원       경찰병원
18          고덕         고덕
19         고려대        고려대
20       고속터미널      고속터미널
21          공덕         공덕
22          공릉         공릉
23        공항시장       공항시장
24         광나루        광나루
25         광운대        광운대
26         광화문        광화문
27         광흥창        광흥창
28          교대         교대
29          구로         구로
30     구로디지털단지    구로디지털단지
31         구반포        구반포
32          구산         구산
33          구의         구의
34         구파발        구파발
35       국회의사당      국회의사당
36          군자         군자
37        굽은다리       굽은다리
38        금천구청       금천구청
39          금호         금호
40          길동         길동
41          길음         길음
42        김포공항       김포공항
43         까치산        까치산
44         낙성대        낙성대
45         남구로        남구로
46       남부터미널      남부터미널
47          남성         남성
48          남영         남영
49         남태령        남태령
50          내방         내방
51         노량진        노량진
52          노원         노원
53          논현         논현
54         답십리        답십리
55         당고개        당고개
56          당산         당산
57          대림         대림
58          대방         대방
59          대치         대치
60          대흥         대흥
61          도봉         도봉
62         도봉산        도봉산
63         독립문        독립문
64          독산         독산
65         돌곶이        돌곶이
66         동대문        동대문
67   동대문역사문화공원  동대문역사문화공원
68         동묘앞        동묘앞
69          둔촌         둔촌
70         둔촌동        둔촌동
71          등촌         등촌
72    디지털미디어시티   디지털미디어시티
73          뚝섬         뚝섬
74       뚝섬유원지      뚝섬유원지
75          마곡         마곡
76          마들         마들
77          마장         마장
78          마천         마천
79          마포         마포
80        마포구청       마포구청
81          망우         망우
82          망원         망원
83          매봉         매봉
84          먹골         먹골
85          면목         면목
86          명동         명동
87          명일         명일
88          목동         목동
89        몽촌토성       몽촌토성
90          문래         문래
91          문정         문정
92          미아         미아
93       미아사거리      미아사거리
94          발산         발산
95          방배         방배
96          방이         방이
97          방학         방학
98          방화         방화
99        버티고개       버티고개
100        보라매        보라매
101         보문         보문
102        봉은사        봉은사
103         봉천         봉천
104     북한산보국문     북한산보국문
105      북한산우이      북한산우이
106         불광         불광
107        사가정        사가정
108         사당         사당
109        삼각지        삼각지
110         삼성         삼성
111       삼성중앙       삼성중앙
112      삼양사거리      삼양사거리
113         삼전         삼전
114         상계         상계
115         상도         상도
116         상봉         상봉
117         상수         상수
118       상왕십리       상왕십리
119        상월곡        상월곡
120         새절         새절
121        서강대        서강대
122        서대문        서대문
123        서빙고        서빙고
124         서울         서울
125      서울대입구      서울대입구
126        서울숲        서울숲
127         서초         서초
128         석계         석계
129         석수         석수
130         석촌         석촌
131       석촌고분       석촌고분
132         선릉         선릉
133        선유도        선유도
134        선정릉        선정릉
135         성수         성수
136     성신여대입구     성신여대입구
137       솔밭공원       솔밭공원
138         송정         송정
139         송파         송파
140       송파나루       송파나루
141        수락산        수락산
142         수색         수색
143         수서         수서
144         수유         수유
145       숙대입구       숙대입구
146      숭실대입구      숭실대입구
147         시청         시청
148        신금호        신금호
149         신길         신길
150         신내         신내
151        신논현        신논현
152         신당         신당
153        신대방        신대방
154     신대방삼거리     신대방삼거리
155        신도림        신도림
156         신림         신림
157        신목동        신목동
158        신방화        신방화
159         신사         신사
160        신설동        신설동
161        신용산        신용산
162         신정         신정
163      신정네거리      신정네거리
164         신촌         신촌
165         신풍         신풍
166         쌍문         쌍문
167        아차산        아차산
168         아현         아현
169         안국         안국
170         안암         안암
171         암사         암사
172        압구정        압구정
173     압구정로데오     압구정로데오
174        애오개        애오개
175         약수         약수
176         양재         양재
177     양재시민의숲     양재시민의숲
178       양천향교       양천향교
179         양평         양평
180     어린이대공원     어린이대공원
181         언주         언주
182        여의도        여의도
183         역삼         역삼
184         역촌         역촌
185        연신내        연신내
186         염창         염창
187        영등포        영등포
188      영등포구청      영등포구청
189      영등포시장      영등포시장
190         오금         오금
191        오류동        오류동
192        오목교        오목교
193         옥수         옥수
194         온수         온수
195        왕십리        왕십리
196        외대앞        외대앞
197         용산         용산
198        우장산        우장산
199         월계         월계
200         월곡         월곡
201     월드컵경기장     월드컵경기장
202      을지로3가      을지로3가
203      을지로4가      을지로4가
204      을지로입구      을지로입구
205         응암         응암
206         이대         이대
207         이수         이수
208        이태원        이태원
209         잠실         잠실
210       잠실나루       잠실나루
211       잠실새내       잠실새내
212         잠원         잠원
213       장승배기       장승배기
214         장지         장지
215        장한평        장한평
216         정릉         정릉
217        제기동        제기동
218         종각         종각
219       종로3가       종로3가
220       종로5가       종로5가
221         중곡         중곡
222         중랑         중랑
223         중화         중화
224         증산         증산
225         창동         창동
226         창신         창신
227         천왕         천왕
228         천호         천호
229      청계산입구      청계산입구
230         청구         청구
231         청담         청담
232        청량리        청량리
233      총신대입구      총신대입구
234        충무로        충무로
235        충정로        충정로
236       태릉입구       태릉입구
237         학동         학동
238        한강진        한강진
239      한성대입구      한성대입구
240       한성백제       한성백제
241        한양대        한양대
242         한티         한티
243         합정         합정
244         행당         행당
245         혜화         혜화
246       홍대입구       홍대입구
247         홍제         홍제
248         화계         화계
249         화곡         화곡
250        화랑대        화랑대
251         회기         회기
252         회현         회현
253      효창공원앞      효창공원앞

In [28]:
new_df[new_df['상권_코드_명'].isin(another_df['상권_코드_명'])==False]

Empty DataFrame
Columns: [상권_코드_명]
Index: []

In [29]:
new_df.to_csv('./2020_매출데이터_상권코드명_지하철역_모든업종.csv', encoding='cp949', index=False)